name: Generate Pacman Game

on:
  schedule:
    - cron: "0 0 * * *" # Run once daily at 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pacman contribution graphs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: AhmedYasserEssam

      - name: Push generated graphs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
